from typing import Any, Iterable

class Module:
    def eval(self) -> "Module": ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def modules(self) -> Iterable["Module"]: ...

class Linear(Module):
    weight: Any
    bias: Any
    def __init__(self, in_features: int, out_features: int) -> None: ...

class ReLU(Module):
    ...

class Dropout(Module):
    def __init__(self, p: float = 0.5) -> None: ...

class Softmax(Module):
    def __init__(self, dim: int = -1) -> None: ...

class Sequential(Module):
    def __init__(self, *args: Module) -> None: ...
    def modules(self) -> Iterable[Module]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class init:
    @staticmethod
    def kaiming_normal_(tensor: Any, mode: str = "fan_in", nonlinearity: str = "relu") -> None: ...
    @staticmethod
    def zeros_(tensor: Any) -> None: ...
