from typing import Any, ContextManager

class Tensor:
    def float(self) -> "Tensor": ...
    def numpy(self) -> Any: ...

class Module:
    def eval(self) -> "Module": ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def from_numpy(arr: Any) -> Tensor: ...
def no_grad() -> ContextManager[Any]: ...
