from typing import Any

class ndarray:
    ...

class cuda:
    class runtime:
        @staticmethod
        def getDeviceCount() -> int: ...

def asnumpy(arr: ndarray) -> Any: ...
def asarray(arr: Any) -> ndarray: ...
